from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save , pre_save
from django.core.validators import MinValueValidator , MaxValueValidator
from datetime import datetime
from django.utils import timezone
from django.core.validators import RegexValidator
from django.utils.text import slugify
from django.utils.translation import gettext as _


class Visitor(models.Model):


    user = models.OneToOneField(User, on_delete = models.CASCADE, related_name='customer')
    name = models.CharField(max_length=50)
    slug_name = models.SlugField(blank=True ,  null = True)
    email = models.EmailField(blank=True ,  null = True)
    phone = models.CharField(max_length=11,validators = [RegexValidator(regex = r"^[0][5][0|2|3|4|5|9][-][0-9]{7}$" ,message="Phone number must be entered in the right format: 05X-XXXXXXX .")],blank=True ,  null = True)
    address = models.CharField(max_length=100 , blank=True ,  null = True)
    city = models.CharField(max_length=100 , blank=True ,  null = True)
    country = models.CharField(max_length=10 , blank=True ,  null = True)
    age = models.IntegerField(validators=[MinValueValidator(18), MaxValueValidator(120)] ,blank=True ,  null = True)
    url = models.CharField(max_length = 3000, blank=True ,  null = True)
    creation_date = models.DateField(auto_now_add=True )
    

    
    def __str__(self):
        COUNTRIES = (
            (None, _('None')),
            ('AD', _('Andorra')),
            ('AE', _('United Arab Emirates')),
            ('AF', _('Afghanistan')),
            ('AG', _('Antigua & Barbuda')),
            ('AI', _('Anguilla')),
            ('AL', _('Albania')),
            ('AM', _('Armenia')),
            ('AN', _('Netherlands Antilles')),
            ('AO', _('Angola')),
            ('AQ', _('Antarctica')),
            ('AR', _('Argentina')),
            ('AS', _('American Samoa')),
            ('AT', _('Austria')),
            ('AU', _('Australia')),
            ('AW', _('Aruba')),
            ('AZ', _('Azerbaijan')),
            ('BA', _('Bosnia and Herzegovina')),
            ('BB', _('Barbados')),
            ('BD', _('Bangladesh')),
            ('BE', _('Belgium')),
            ('BF', _('Burkina Faso')),
            ('BG', _('Bulgaria')),
            ('BH', _('Bahrain')),
            ('BI', _('Burundi')),
            ('BJ', _('Benin')),
            ('BM', _('Bermuda')),
            ('BN', _('Brunei Darussalam')),
            ('BO', _('Bolivia')),
            ('BR', _('Brazil')),
            ('BS', _('Bahama')),
            ('BT', _('Bhutan')),
            ('BV', _('Bouvet Island')),
            ('BW', _('Botswana')),
            ('BY', _('Belarus')),
            ('BZ', _('Belize')),
            ('CA', _('Canada')),
            ('CC', _('Cocos (Keeling) Islands')),
            ('CF', _('Central African Republic')),
            ('CG', _('Congo')),
            ('CH', _('Switzerland')),
            ('CI', _('Ivory Coast')),
            ('CK', _('Cook Iislands')),
            ('CL', _('Chile')),
            ('CM', _('Cameroon')),
            ('CN', _('China')),
            ('CO', _('Colombia')),
            ('CR', _('Costa Rica')),
            ('CU', _('Cuba')),
            ('CV', _('Cape Verde')),
            ('CX', _('Christmas Island')),
            ('CY', _('Cyprus')),
            ('CZ', _('Czech Republic')),
            ('DE', _('Germany')),
            ('DJ', _('Djibouti')),
            ('DK', _('Denmark')),
            ('DM', _('Dominica')),
            ('DO', _('Dominican Republic')),
            ('DZ', _('Algeria')),
            ('EC', _('Ecuador')),
            ('EE', _('Estonia')),
            ('EG', _('Egypt')),
            ('EH', _('Western Sahara')),
            ('ER', _('Eritrea')),
            ('ES', _('Spain')),
            ('ET', _('Ethiopia')),
            ('FI', _('Finland')),
            ('FJ', _('Fiji')),
            ('FK', _('Falkland Islands (Malvinas)')),
            ('FM', _('Micronesia')),
            ('FO', _('Faroe Islands')),
            ('FR', _('France')),
            ('FX', _('France, Metropolitan')),
            ('GA', _('Gabon')),
            ('GB', _('United Kingdom (Great Britain)')),
            ('GD', _('Grenada')),
            ('GE', _('Georgia')),
            ('GF', _('French Guiana')),
            ('GH', _('Ghana')),
            ('GI', _('Gibraltar')),
            ('GL', _('Greenland')),
            ('GM', _('Gambia')),
            ('GN', _('Guinea')),
            ('GP', _('Guadeloupe')),
            ('GQ', _('Equatorial Guinea')),
            ('GR', _('Greece')),
            ('GS', _('South Georgia and the South Sandwich Islands')),
            ('GT', _('Guatemala')),
            ('GU', _('Guam')),
            ('GW', _('Guinea-Bissau')),
            ('GY', _('Guyana')),
            ('HK', _('Hong Kong')),
            ('HM', _('Heard & McDonald Islands')),
            ('HN', _('Honduras')),
            ('HR', _('Croatia')),
            ('HT', _('Haiti')),
            ('HU', _('Hungary')),
            ('ID', _('Indonesia')),
            ('IE', _('Ireland')),
            ('IL', _('Israel')),
            ('IN', _('India')),
            ('IO', _('British Indian Ocean Territory')),
            ('IQ', _('Iraq')),
            ('IR', _('Islamic Republic of Iran')),
            ('IS', _('Iceland')),
            ('IT', _('Italy')),
            ('JM', _('Jamaica')),
            ('JO', _('Jordan')),
            ('JP', _('Japan')),
            ('KE', _('Kenya')),
            ('KG', _('Kyrgyzstan')),
            ('KH', _('Cambodia')),
            ('KI', _('Kiribati')),
            ('KM', _('Comoros')),
            ('KN', _('St. Kitts and Nevis')),
            ('KP', _('Korea, Democratic People\'s Republic of')),
            ('KR', _('Korea, Republic of')),
            ('KW', _('Kuwait')),
            ('KY', _('Cayman Islands')),
            ('KZ', _('Kazakhstan')),
            ('LA', _('Lao People\'s Democratic Republic')),
            ('LB', _('Lebanon')),
            ('LC', _('Saint Lucia')),
            ('LI', _('Liechtenstein')),
            ('LK', _('Sri Lanka')),
            ('LR', _('Liberia')),
            ('LS', _('Lesotho')),
            ('LT', _('Lithuania')),
            ('LU', _('Luxembourg')),
            ('LV', _('Latvia')),
            ('LY', _('Libyan Arab Jamahiriya')),
            ('MA', _('Morocco')),
            ('MC', _('Monaco')),
            ('MD', _('Moldova, Republic of')),
            ('MG', _('Madagascar')),
            ('MH', _('Marshall Islands')),
            ('ML', _('Mali')),
            ('MN', _('Mongolia')),
            ('MM', _('Myanmar')),
            ('MO', _('Macau')),
            ('MP', _('Northern Mariana Islands')),
            ('MQ', _('Martinique')),
            ('MR', _('Mauritania')),
            ('MS', _('Monserrat')),
            ('MT', _('Malta')),
            ('MU', _('Mauritius')),
            ('MV', _('Maldives')),
            ('MW', _('Malawi')),
            ('MX', _('Mexico')),
            ('MY', _('Malaysia')),
            ('MZ', _('Mozambique')),
            ('NA', _('Namibia')),
            ('NC', _('New Caledonia')),
            ('NE', _('Niger')),
            ('NF', _('Norfolk Island')),
            ('NG', _('Nigeria')),
            ('NI', _('Nicaragua')),
            ('NL', _('Netherlands')),
            ('NO', _('Norway')),
            ('NP', _('Nepal')),
            ('NR', _('Nauru')),
            ('NU', _('Niue')),
            ('NZ', _('New Zealand')),
            ('OM', _('Oman')),
            ('PA', _('Panama')),
            ('PE', _('Peru')),
            ('PF', _('French Polynesia')),
            ('PG', _('Papua New Guinea')),
            ('PH', _('Philippines')),
            ('PK', _('Pakistan')),
            ('PL', _('Poland')),
            ('PM', _('St. Pierre & Miquelon')),
            ('PN', _('Pitcairn')),
            ('PR', _('Puerto Rico')),
            ('PT', _('Portugal')),
            ('PW', _('Palau')),
            ('PY', _('Paraguay')),
            ('QA', _('Qatar')),
            ('RE', _('Reunion')),
            ('RO', _('Romania')),
            ('RU', _('Russian Federation')),
            ('RW', _('Rwanda')),
            ('SA', _('Saudi Arabia')),
            ('SB', _('Solomon Islands')),
            ('SC', _('Seychelles')),
            ('SD', _('Sudan')),
            ('SE', _('Sweden')),
            ('SG', _('Singapore')),
            ('SH', _('St. Helena')),
            ('SI', _('Slovenia')),
            ('SJ', _('Svalbard & Jan Mayen Islands')),
            ('SK', _('Slovakia')),
            ('SL', _('Sierra Leone')),
            ('SM', _('San Marino')),
            ('SN', _('Senegal')),
            ('SO', _('Somalia')),
            ('SR', _('Suriname')),
            ('ST', _('Sao Tome & Principe')),
            ('SV', _('El Salvador')),
            ('SY', _('Syrian Arab Republic')),
            ('SZ', _('Swaziland')),
            ('TC', _('Turks & Caicos Islands')),
            ('TD', _('Chad')),
            ('TF', _('French Southern Territories')),
            ('TG', _('Togo')),
            ('TH', _('Thailand')),
            ('TJ', _('Tajikistan')),
            ('TK', _('Tokelau')),
            ('TM', _('Turkmenistan')),
            ('TN', _('Tunisia')),
            ('TO', _('Tonga')),
            ('TP', _('East Timor')),
            ('TR', _('Turkey')),
            ('TT', _('Trinidad & Tobago')),
            ('TV', _('Tuvalu')),
            ('TW', _('Taiwan, Province of China')),
            ('TZ', _('Tanzania, United Republic of')),
            ('UA', _('Ukraine')),
            ('UG', _('Uganda')),
            ('UM', _('United States Minor Outlying Islands')),
            ('US', _('United States of America')),
            ('UY', _('Uruguay')),
            ('UZ', _('Uzbekistan')),
            ('VA', _('Vatican City State (Holy See)')),
            ('VC', _('St. Vincent & the Grenadines')),
            ('VE', _('Venezuela')),
            ('VG', _('British Virgin Islands')),
            ('VI', _('United States Virgin Islands')),
            ('VN', _('Viet Nam')),
            ('VU', _('Vanuatu')),
            ('WF', _('Wallis & Futuna Islands')),
            ('WS', _('Samoa')),
            ('YE', _('Yemen')),
            ('YT', _('Mayotte')),
            ('YU', _('Yugoslavia')),
            ('ZA', _('South Africa')),
            ('ZM', _('Zambia')),
            ('ZR', _('Zaire')),
            ('ZW', _('Zimbabwe')),
            ('ZZ', _('Unknown or unspecified country')),
        ) 

        return f""" 
        Name: {self.slug_name} , 
        Email: {self.email} ,
        Phone Number: {self.phone} ,
        Address: {self.address} , 
        City: {self.city} , 
        Country: {dict(COUNTRIES)[self.country]} , 
        Age: {self.age} ,
        Upload File: {self.url} ,
        Created At: {self.creation_date}"""


    def save(self,*args,**kwargs):
        self.slug_name = slugify(self.name)
        super(Visitor,self).save(*args,**kwargs)


def post_profile_group(sender, instance, created, *args, **kwargs):
    if created:
        if not instance.is_staff :
            v = Visitor.objects.create(user_id = instance.id)
            Group.objects.get(name='Visitors').user_set.add(instance)
        else:
            Group.objects.get(name='Staff').user_set.add(instance)
post_save.connect(receiver=post_profile_group, sender=User)

