# Generated by Django 4.0.6 on 2022-11-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_loan_borrow_date_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
