# Generated by Django 4.0.6 on 2022-09-30 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('visitors', '0005_book_book_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(blank=True, default=datetime.datetime(2022, 9, 30, 16, 46, 25, 341524))),
                ('return_date', models.DateField(blank=True)),
                ('books', models.ManyToManyField(related_name='loans', to='visitors.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor')),
            ],
        ),
    ]
