# Generated by Django 4.0.6 on 2022-09-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='bla',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
