# Generated by Django 4.0.6 on 2022-09-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_visitor_bla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='phone',
        ),
    ]
