# Generated by Django 4.0.6 on 2022-09-20 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_visitor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='bla',
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the right format .', regex='^[0][5][0|2|3|4|5|9][-][0-9]{7}$')]),
        ),
    ]
