# Generated by Django 4.0.6 on 2022-09-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_delete_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
